// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: api/v1/sync.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncService_Write_FullMethodName         = "/api.v1.SyncService/Write"
	SyncService_CompareHashes_FullMethodName = "/api.v1.SyncService/CompareHashes"
	SyncService_Commit_FullMethodName        = "/api.v1.SyncService/Commit"
	SyncService_Delete_FullMethodName        = "/api.v1.SyncService/Delete"
	SyncService_Done_FullMethodName          = "/api.v1.SyncService/Done"
)

// SyncServiceClient is the client API for SyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SyncService consolidates all data-path RPCs.
type SyncServiceClient interface {
	// Bidi-streaming RPCs
	Write(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WriteRequest, WriteResponse], error)
	CompareHashes(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HashRequest, HashResponse], error)
	Commit(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommitRequest, CommitResponse], error)
	Delete(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DeleteRequest, DeleteResponse], error)
	// Unary RPCs
	Done(ctx context.Context, in *DoneRequest, opts ...grpc.CallOption) (*DoneResponse, error)
}

type syncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncServiceClient(cc grpc.ClientConnInterface) SyncServiceClient {
	return &syncServiceClient{cc}
}

func (c *syncServiceClient) Write(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WriteRequest, WriteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SyncService_ServiceDesc.Streams[0], SyncService_Write_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteRequest, WriteResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncService_WriteClient = grpc.BidiStreamingClient[WriteRequest, WriteResponse]

func (c *syncServiceClient) CompareHashes(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HashRequest, HashResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SyncService_ServiceDesc.Streams[1], SyncService_CompareHashes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HashRequest, HashResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncService_CompareHashesClient = grpc.BidiStreamingClient[HashRequest, HashResponse]

func (c *syncServiceClient) Commit(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommitRequest, CommitResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SyncService_ServiceDesc.Streams[2], SyncService_Commit_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CommitRequest, CommitResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncService_CommitClient = grpc.BidiStreamingClient[CommitRequest, CommitResponse]

func (c *syncServiceClient) Delete(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DeleteRequest, DeleteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SyncService_ServiceDesc.Streams[3], SyncService_Delete_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DeleteRequest, DeleteResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncService_DeleteClient = grpc.BidiStreamingClient[DeleteRequest, DeleteResponse]

func (c *syncServiceClient) Done(ctx context.Context, in *DoneRequest, opts ...grpc.CallOption) (*DoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoneResponse)
	err := c.cc.Invoke(ctx, SyncService_Done_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncServiceServer is the server API for SyncService service.
// All implementations must embed UnimplementedSyncServiceServer
// for forward compatibility.
//
// SyncService consolidates all data-path RPCs.
type SyncServiceServer interface {
	// Bidi-streaming RPCs
	Write(grpc.BidiStreamingServer[WriteRequest, WriteResponse]) error
	CompareHashes(grpc.BidiStreamingServer[HashRequest, HashResponse]) error
	Commit(grpc.BidiStreamingServer[CommitRequest, CommitResponse]) error
	Delete(grpc.BidiStreamingServer[DeleteRequest, DeleteResponse]) error
	// Unary RPCs
	Done(context.Context, *DoneRequest) (*DoneResponse, error)
	mustEmbedUnimplementedSyncServiceServer()
}

// UnimplementedSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncServiceServer struct{}

func (UnimplementedSyncServiceServer) Write(grpc.BidiStreamingServer[WriteRequest, WriteResponse]) error {
	return status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedSyncServiceServer) CompareHashes(grpc.BidiStreamingServer[HashRequest, HashResponse]) error {
	return status.Error(codes.Unimplemented, "method CompareHashes not implemented")
}
func (UnimplementedSyncServiceServer) Commit(grpc.BidiStreamingServer[CommitRequest, CommitResponse]) error {
	return status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedSyncServiceServer) Delete(grpc.BidiStreamingServer[DeleteRequest, DeleteResponse]) error {
	return status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSyncServiceServer) Done(context.Context, *DoneRequest) (*DoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Done not implemented")
}
func (UnimplementedSyncServiceServer) mustEmbedUnimplementedSyncServiceServer() {}
func (UnimplementedSyncServiceServer) testEmbeddedByValue()                     {}

// UnsafeSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncServiceServer will
// result in compilation errors.
type UnsafeSyncServiceServer interface {
	mustEmbedUnimplementedSyncServiceServer()
}

func RegisterSyncServiceServer(s grpc.ServiceRegistrar, srv SyncServiceServer) {
	// If the following call panics, it indicates UnimplementedSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncService_ServiceDesc, srv)
}

func _SyncService_Write_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SyncServiceServer).Write(&grpc.GenericServerStream[WriteRequest, WriteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncService_WriteServer = grpc.BidiStreamingServer[WriteRequest, WriteResponse]

func _SyncService_CompareHashes_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SyncServiceServer).CompareHashes(&grpc.GenericServerStream[HashRequest, HashResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncService_CompareHashesServer = grpc.BidiStreamingServer[HashRequest, HashResponse]

func _SyncService_Commit_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SyncServiceServer).Commit(&grpc.GenericServerStream[CommitRequest, CommitResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncService_CommitServer = grpc.BidiStreamingServer[CommitRequest, CommitResponse]

func _SyncService_Delete_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SyncServiceServer).Delete(&grpc.GenericServerStream[DeleteRequest, DeleteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncService_DeleteServer = grpc.BidiStreamingServer[DeleteRequest, DeleteResponse]

func _SyncService_Done_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).Done(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_Done_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).Done(ctx, req.(*DoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncService_ServiceDesc is the grpc.ServiceDesc for SyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.SyncService",
	HandlerType: (*SyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Done",
			Handler:    _SyncService_Done_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Write",
			Handler:       _SyncService_Write_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CompareHashes",
			Handler:       _SyncService_CompareHashes_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Commit",
			Handler:       _SyncService_Commit_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Delete",
			Handler:       _SyncService_Delete_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/v1/sync.proto",
}
