// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/v1/sync.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CompressionAlgo specifies the compression format.
type CompressionAlgo int32

const (
	CompressionAlgo_COMPRESSION_NONE CompressionAlgo = 0
	CompressionAlgo_COMPRESSION_LZ4  CompressionAlgo = 1
)

// Enum value maps for CompressionAlgo.
var (
	CompressionAlgo_name = map[int32]string{
		0: "COMPRESSION_NONE",
		1: "COMPRESSION_LZ4",
	}
	CompressionAlgo_value = map[string]int32{
		"COMPRESSION_NONE": 0,
		"COMPRESSION_LZ4":  1,
	}
)

func (x CompressionAlgo) Enum() *CompressionAlgo {
	p := new(CompressionAlgo)
	*p = x
	return p
}

func (x CompressionAlgo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompressionAlgo) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_sync_proto_enumTypes[0].Descriptor()
}

func (CompressionAlgo) Type() protoreflect.EnumType {
	return &file_api_v1_sync_proto_enumTypes[0]
}

func (x CompressionAlgo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompressionAlgo.Descriptor instead.
func (CompressionAlgo) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{0}
}

// ChangedBlock represents a modified data range.
type ChangedBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID for deduplication and tracking.
	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Path of the file or device being written.
	FilePath string `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	// Total size of the file or device in bytes.
	TotalSize uint64 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	// Byte offset where the write should begin.
	Offset uint64 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	// Length of the write in bytes.
	Length uint64 `protobuf:"varint,5,opt,name=length,proto3" json:"length,omitempty"`
	// Indicates this write represents a zeroed range.
	IsZero bool `protobuf:"varint,6,opt,name=is_zero,json=isZero,proto3" json:"is_zero,omitempty"`
	// Data payload. May be empty if is_zero is true.
	Data []byte `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	// Compression algorithm applied to data.
	Compression   CompressionAlgo `protobuf:"varint,8,opt,name=compression,proto3,enum=api.v1.CompressionAlgo" json:"compression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangedBlock) Reset() {
	*x = ChangedBlock{}
	mi := &file_api_v1_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangedBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangedBlock) ProtoMessage() {}

func (x *ChangedBlock) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangedBlock.ProtoReflect.Descriptor instead.
func (*ChangedBlock) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{0}
}

func (x *ChangedBlock) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ChangedBlock) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ChangedBlock) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ChangedBlock) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ChangedBlock) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ChangedBlock) GetIsZero() bool {
	if x != nil {
		return x.IsZero
	}
	return false
}

func (x *ChangedBlock) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChangedBlock) GetCompression() CompressionAlgo {
	if x != nil {
		return x.Compression
	}
	return CompressionAlgo_COMPRESSION_NONE
}

// WriteRequest represents a batched write operation.
type WriteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of changed blocks to be written.
	Blocks        []*ChangedBlock `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_api_v1_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{1}
}

func (x *WriteRequest) GetBlocks() []*ChangedBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

// WriteResponse carries acknowledged request IDs
// for window release on the source side.
type WriteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request IDs that the destination has processed.
	AcknowledgedIds []uint64 `protobuf:"varint,1,rep,packed,name=acknowledged_ids,json=acknowledgedIds,proto3" json:"acknowledged_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_api_v1_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{2}
}

func (x *WriteResponse) GetAcknowledgedIds() []uint64 {
	if x != nil {
		return x.AcknowledgedIds
	}
	return nil
}

// DeleteRequest represents a batch deletion.
type DeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Paths to delete (recursive by default).
	Paths         []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_v1_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

// DeleteResponse is empty on success.
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_v1_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{4}
}

// BlockHash represents a hash of a single block for comparison.
type BlockHash struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID for tracking and correlating responses.
	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Path of the file or device being compared.
	FilePath string `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	// Total size of the file or device in bytes.
	TotalSize uint64 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	// Byte offset of the block within the file or device.
	Offset uint64 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	// Length of the block in bytes.
	Length uint64 `protobuf:"varint,5,opt,name=length,proto3" json:"length,omitempty"`
	// SHA-256 hash of the block data.
	Sha256        []byte `protobuf:"bytes,6,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockHash) Reset() {
	*x = BlockHash{}
	mi := &file_api_v1_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHash) ProtoMessage() {}

func (x *BlockHash) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHash.ProtoReflect.Descriptor instead.
func (*BlockHash) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{5}
}

func (x *BlockHash) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *BlockHash) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *BlockHash) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *BlockHash) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *BlockHash) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *BlockHash) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

// HashRequest carries a batch of block hashes to compare.
type HashRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of block hashes to be compared on the destination.
	Hashes        []*BlockHash `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashRequest) Reset() {
	*x = HashRequest{}
	mi := &file_api_v1_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashRequest) ProtoMessage() {}

func (x *HashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashRequest.ProtoReflect.Descriptor instead.
func (*HashRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{6}
}

func (x *HashRequest) GetHashes() []*BlockHash {
	if x != nil {
		return x.Hashes
	}
	return nil
}

// HashResponse reports which blocks did not match.
type HashResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request IDs of blocks whose hashes did not match.
	MismatchedIds []uint64 `protobuf:"varint,1,rep,packed,name=mismatched_ids,json=mismatchedIds,proto3" json:"mismatched_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashResponse) Reset() {
	*x = HashResponse{}
	mi := &file_api_v1_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashResponse) ProtoMessage() {}

func (x *HashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashResponse.ProtoReflect.Descriptor instead.
func (*HashResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{7}
}

func (x *HashResponse) GetMismatchedIds() []uint64 {
	if x != nil {
		return x.MismatchedIds
	}
	return nil
}

// CommitEntry represents a single file to commit.
type CommitEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target path of the file to commit.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Total size of the file or device in bytes.
	TotalSize     uint64 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitEntry) Reset() {
	*x = CommitEntry{}
	mi := &file_api_v1_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitEntry) ProtoMessage() {}

func (x *CommitEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitEntry.ProtoReflect.Descriptor instead.
func (*CommitEntry) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{8}
}

func (x *CommitEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CommitEntry) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// CommitRequest contains a batch of files to commit.
type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*CommitEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_api_v1_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{9}
}

func (x *CommitRequest) GetEntries() []*CommitEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// CommitResponse confirms committed file paths.
type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_api_v1_sync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{10}
}

func (x *CommitResponse) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

// DoneRequest signals completion.
type DoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoneRequest) Reset() {
	*x = DoneRequest{}
	mi := &file_api_v1_sync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoneRequest) ProtoMessage() {}

func (x *DoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoneRequest.ProtoReflect.Descriptor instead.
func (*DoneRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{11}
}

// DoneResponse is empty on success.
type DoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoneResponse) Reset() {
	*x = DoneResponse{}
	mi := &file_api_v1_sync_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoneResponse) ProtoMessage() {}

func (x *DoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoneResponse.ProtoReflect.Descriptor instead.
func (*DoneResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{12}
}

var File_api_v1_sync_proto protoreflect.FileDescriptor

const file_api_v1_sync_proto_rawDesc = "" +
	"\n" +
	"\x11api/v1/sync.proto\x12\x06api.v1\"\x81\x02\n" +
	"\fChangedBlock\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x04R\ttotalSize\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x05 \x01(\x04R\x06length\x12\x17\n" +
	"\ais_zero\x18\x06 \x01(\bR\x06isZero\x12\x12\n" +
	"\x04data\x18\a \x01(\fR\x04data\x129\n" +
	"\vcompression\x18\b \x01(\x0e2\x17.api.v1.CompressionAlgoR\vcompression\"<\n" +
	"\fWriteRequest\x12,\n" +
	"\x06blocks\x18\x01 \x03(\v2\x14.api.v1.ChangedBlockR\x06blocks\":\n" +
	"\rWriteResponse\x12)\n" +
	"\x10acknowledged_ids\x18\x01 \x03(\x04R\x0facknowledgedIds\"%\n" +
	"\rDeleteRequest\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\"\x10\n" +
	"\x0eDeleteResponse\"\xae\x01\n" +
	"\tBlockHash\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x04R\ttotalSize\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x05 \x01(\x04R\x06length\x12\x16\n" +
	"\x06sha256\x18\x06 \x01(\fR\x06sha256\"8\n" +
	"\vHashRequest\x12)\n" +
	"\x06hashes\x18\x01 \x03(\v2\x11.api.v1.BlockHashR\x06hashes\"5\n" +
	"\fHashResponse\x12%\n" +
	"\x0emismatched_ids\x18\x01 \x03(\x04R\rmismatchedIds\"@\n" +
	"\vCommitEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x04R\ttotalSize\">\n" +
	"\rCommitRequest\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.api.v1.CommitEntryR\aentries\"&\n" +
	"\x0eCommitResponse\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\"\r\n" +
	"\vDoneRequest\"\x0e\n" +
	"\fDoneResponse*<\n" +
	"\x0fCompressionAlgo\x12\x14\n" +
	"\x10COMPRESSION_NONE\x10\x00\x12\x13\n" +
	"\x0fCOMPRESSION_LZ4\x10\x012\xb4\x02\n" +
	"\vSyncService\x128\n" +
	"\x05Write\x12\x14.api.v1.WriteRequest\x1a\x15.api.v1.WriteResponse(\x010\x01\x12>\n" +
	"\rCompareHashes\x12\x13.api.v1.HashRequest\x1a\x14.api.v1.HashResponse(\x010\x01\x12;\n" +
	"\x06Commit\x12\x15.api.v1.CommitRequest\x1a\x16.api.v1.CommitResponse(\x010\x01\x12;\n" +
	"\x06Delete\x12\x15.api.v1.DeleteRequest\x1a\x16.api.v1.DeleteResponse(\x010\x01\x121\n" +
	"\x04Done\x12\x13.api.v1.DoneRequest\x1a\x14.api.v1.DoneResponseB>Z<github.com/RamenDR/ceph-volsync-plugin/internal/proto/api/v1b\x06proto3"

var (
	file_api_v1_sync_proto_rawDescOnce sync.Once
	file_api_v1_sync_proto_rawDescData []byte
)

func file_api_v1_sync_proto_rawDescGZIP() []byte {
	file_api_v1_sync_proto_rawDescOnce.Do(func() {
		file_api_v1_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_sync_proto_rawDesc), len(file_api_v1_sync_proto_rawDesc)))
	})
	return file_api_v1_sync_proto_rawDescData
}

var file_api_v1_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_v1_sync_proto_goTypes = []any{
	(CompressionAlgo)(0),   // 0: api.v1.CompressionAlgo
	(*ChangedBlock)(nil),   // 1: api.v1.ChangedBlock
	(*WriteRequest)(nil),   // 2: api.v1.WriteRequest
	(*WriteResponse)(nil),  // 3: api.v1.WriteResponse
	(*DeleteRequest)(nil),  // 4: api.v1.DeleteRequest
	(*DeleteResponse)(nil), // 5: api.v1.DeleteResponse
	(*BlockHash)(nil),      // 6: api.v1.BlockHash
	(*HashRequest)(nil),    // 7: api.v1.HashRequest
	(*HashResponse)(nil),   // 8: api.v1.HashResponse
	(*CommitEntry)(nil),    // 9: api.v1.CommitEntry
	(*CommitRequest)(nil),  // 10: api.v1.CommitRequest
	(*CommitResponse)(nil), // 11: api.v1.CommitResponse
	(*DoneRequest)(nil),    // 12: api.v1.DoneRequest
	(*DoneResponse)(nil),   // 13: api.v1.DoneResponse
}
var file_api_v1_sync_proto_depIdxs = []int32{
	0,  // 0: api.v1.ChangedBlock.compression:type_name -> api.v1.CompressionAlgo
	1,  // 1: api.v1.WriteRequest.blocks:type_name -> api.v1.ChangedBlock
	6,  // 2: api.v1.HashRequest.hashes:type_name -> api.v1.BlockHash
	9,  // 3: api.v1.CommitRequest.entries:type_name -> api.v1.CommitEntry
	2,  // 4: api.v1.SyncService.Write:input_type -> api.v1.WriteRequest
	7,  // 5: api.v1.SyncService.CompareHashes:input_type -> api.v1.HashRequest
	10, // 6: api.v1.SyncService.Commit:input_type -> api.v1.CommitRequest
	4,  // 7: api.v1.SyncService.Delete:input_type -> api.v1.DeleteRequest
	12, // 8: api.v1.SyncService.Done:input_type -> api.v1.DoneRequest
	3,  // 9: api.v1.SyncService.Write:output_type -> api.v1.WriteResponse
	8,  // 10: api.v1.SyncService.CompareHashes:output_type -> api.v1.HashResponse
	11, // 11: api.v1.SyncService.Commit:output_type -> api.v1.CommitResponse
	5,  // 12: api.v1.SyncService.Delete:output_type -> api.v1.DeleteResponse
	13, // 13: api.v1.SyncService.Done:output_type -> api.v1.DoneResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_sync_proto_init() }
func file_api_v1_sync_proto_init() {
	if File_api_v1_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_sync_proto_rawDesc), len(file_api_v1_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_sync_proto_goTypes,
		DependencyIndexes: file_api_v1_sync_proto_depIdxs,
		EnumInfos:         file_api_v1_sync_proto_enumTypes,
		MessageInfos:      file_api_v1_sync_proto_msgTypes,
	}.Build()
	File_api_v1_sync_proto = out.File
	file_api_v1_sync_proto_goTypes = nil
	file_api_v1_sync_proto_depIdxs = nil
}
