// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/v1/sync.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChangedBlock represents a modified data range.
type ChangedBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID for deduplication and tracking.
	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Path of the file or device being written.
	FilePath string `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	// Total size of the file or device in bytes.
	TotalSize uint64 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	// Byte offset where the write should begin.
	Offset uint64 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	// Length of the write in bytes.
	Length uint64 `protobuf:"varint,5,opt,name=length,proto3" json:"length,omitempty"`
	// Indicates this write represents a zeroed range.
	IsZero bool `protobuf:"varint,6,opt,name=is_zero,json=isZero,proto3" json:"is_zero,omitempty"`
	// Data payload. May be empty if is_zero is true.
	Data          []byte `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangedBlock) Reset() {
	*x = ChangedBlock{}
	mi := &file_api_v1_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangedBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangedBlock) ProtoMessage() {}

func (x *ChangedBlock) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangedBlock.ProtoReflect.Descriptor instead.
func (*ChangedBlock) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{0}
}

func (x *ChangedBlock) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ChangedBlock) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ChangedBlock) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ChangedBlock) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ChangedBlock) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ChangedBlock) GetIsZero() bool {
	if x != nil {
		return x.IsZero
	}
	return false
}

func (x *ChangedBlock) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// WriteRequest represents a batched write operation.
type WriteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of changed blocks to be written.
	Blocks        []*ChangedBlock `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_api_v1_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{1}
}

func (x *WriteRequest) GetBlocks() []*ChangedBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

// WriteResponse carries acknowledged request IDs
// for window release on the source side.
type WriteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request IDs that the destination has processed.
	AcknowledgedIds []uint64 `protobuf:"varint,1,rep,packed,name=acknowledged_ids,json=acknowledgedIds,proto3" json:"acknowledged_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_api_v1_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{2}
}

func (x *WriteResponse) GetAcknowledgedIds() []uint64 {
	if x != nil {
		return x.AcknowledgedIds
	}
	return nil
}

// DeleteRequest represents a batch deletion.
type DeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Paths to delete (recursive by default).
	Paths         []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_v1_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

// DeleteResponse is empty on success.
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_v1_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{4}
}

// CommitEntry represents a single file to commit.
type CommitEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target path of the file to commit.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Total size of the file or device in bytes.
	TotalSize     uint64 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitEntry) Reset() {
	*x = CommitEntry{}
	mi := &file_api_v1_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitEntry) ProtoMessage() {}

func (x *CommitEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitEntry.ProtoReflect.Descriptor instead.
func (*CommitEntry) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{5}
}

func (x *CommitEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CommitEntry) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// CommitRequest contains a batch of files to commit.
type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*CommitEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_api_v1_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{6}
}

func (x *CommitRequest) GetEntries() []*CommitEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// CommitResponse confirms committed file paths.
type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_api_v1_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{7}
}

func (x *CommitResponse) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

// DoneRequest signals completion.
type DoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoneRequest) Reset() {
	*x = DoneRequest{}
	mi := &file_api_v1_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoneRequest) ProtoMessage() {}

func (x *DoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoneRequest.ProtoReflect.Descriptor instead.
func (*DoneRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{8}
}

// DoneResponse is empty on success.
type DoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoneResponse) Reset() {
	*x = DoneResponse{}
	mi := &file_api_v1_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoneResponse) ProtoMessage() {}

func (x *DoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoneResponse.ProtoReflect.Descriptor instead.
func (*DoneResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{9}
}

// ExchangeCertsRequest sends the source's ephemeral certificate.
type ExchangeCertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientCertPem []byte                 `protobuf:"bytes,1,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeCertsRequest) Reset() {
	*x = ExchangeCertsRequest{}
	mi := &file_api_v1_sync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeCertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeCertsRequest) ProtoMessage() {}

func (x *ExchangeCertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeCertsRequest.ProtoReflect.Descriptor instead.
func (*ExchangeCertsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{10}
}

func (x *ExchangeCertsRequest) GetClientCertPem() []byte {
	if x != nil {
		return x.ClientCertPem
	}
	return nil
}

// ExchangeCertsResponse returns the destination's ephemeral certificate
// and the port where the direct TLS listener accepts connections.
type ExchangeCertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerCertPem []byte                 `protobuf:"bytes,1,opt,name=server_cert_pem,json=serverCertPem,proto3" json:"server_cert_pem,omitempty"`
	DirectTlsPort int32                  `protobuf:"varint,2,opt,name=direct_tls_port,json=directTlsPort,proto3" json:"direct_tls_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeCertsResponse) Reset() {
	*x = ExchangeCertsResponse{}
	mi := &file_api_v1_sync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeCertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeCertsResponse) ProtoMessage() {}

func (x *ExchangeCertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeCertsResponse.ProtoReflect.Descriptor instead.
func (*ExchangeCertsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_proto_rawDescGZIP(), []int{11}
}

func (x *ExchangeCertsResponse) GetServerCertPem() []byte {
	if x != nil {
		return x.ServerCertPem
	}
	return nil
}

func (x *ExchangeCertsResponse) GetDirectTlsPort() int32 {
	if x != nil {
		return x.DirectTlsPort
	}
	return 0
}

var File_api_v1_sync_proto protoreflect.FileDescriptor

const file_api_v1_sync_proto_rawDesc = "" +
	"\n" +
	"\x11api/v1/sync.proto\x12\x06api.v1\"\xc6\x01\n" +
	"\fChangedBlock\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x04R\ttotalSize\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x05 \x01(\x04R\x06length\x12\x17\n" +
	"\ais_zero\x18\x06 \x01(\bR\x06isZero\x12\x12\n" +
	"\x04data\x18\a \x01(\fR\x04data\"<\n" +
	"\fWriteRequest\x12,\n" +
	"\x06blocks\x18\x01 \x03(\v2\x14.api.v1.ChangedBlockR\x06blocks\":\n" +
	"\rWriteResponse\x12)\n" +
	"\x10acknowledged_ids\x18\x01 \x03(\x04R\x0facknowledgedIds\"%\n" +
	"\rDeleteRequest\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\"\x10\n" +
	"\x0eDeleteResponse\"@\n" +
	"\vCommitEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x04R\ttotalSize\">\n" +
	"\rCommitRequest\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.api.v1.CommitEntryR\aentries\"&\n" +
	"\x0eCommitResponse\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\"\r\n" +
	"\vDoneRequest\"\x0e\n" +
	"\fDoneResponse\">\n" +
	"\x14ExchangeCertsRequest\x12&\n" +
	"\x0fclient_cert_pem\x18\x01 \x01(\fR\rclientCertPem\"g\n" +
	"\x15ExchangeCertsResponse\x12&\n" +
	"\x0fserver_cert_pem\x18\x01 \x01(\fR\rserverCertPem\x12&\n" +
	"\x0fdirect_tls_port\x18\x02 \x01(\x05R\rdirectTlsPort2\xc2\x02\n" +
	"\vSyncService\x128\n" +
	"\x05Write\x12\x14.api.v1.WriteRequest\x1a\x15.api.v1.WriteResponse(\x010\x01\x12;\n" +
	"\x06Commit\x12\x15.api.v1.CommitRequest\x1a\x16.api.v1.CommitResponse(\x010\x01\x12;\n" +
	"\x06Delete\x12\x15.api.v1.DeleteRequest\x1a\x16.api.v1.DeleteResponse(\x010\x01\x121\n" +
	"\x04Done\x12\x13.api.v1.DoneRequest\x1a\x14.api.v1.DoneResponse\x12L\n" +
	"\rExchangeCerts\x12\x1c.api.v1.ExchangeCertsRequest\x1a\x1d.api.v1.ExchangeCertsResponseB>Z<github.com/RamenDR/ceph-volsync-plugin/internal/proto/api/v1b\x06proto3"

var (
	file_api_v1_sync_proto_rawDescOnce sync.Once
	file_api_v1_sync_proto_rawDescData []byte
)

func file_api_v1_sync_proto_rawDescGZIP() []byte {
	file_api_v1_sync_proto_rawDescOnce.Do(func() {
		file_api_v1_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_sync_proto_rawDesc), len(file_api_v1_sync_proto_rawDesc)))
	})
	return file_api_v1_sync_proto_rawDescData
}

var file_api_v1_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_v1_sync_proto_goTypes = []any{
	(*ChangedBlock)(nil),          // 0: api.v1.ChangedBlock
	(*WriteRequest)(nil),          // 1: api.v1.WriteRequest
	(*WriteResponse)(nil),         // 2: api.v1.WriteResponse
	(*DeleteRequest)(nil),         // 3: api.v1.DeleteRequest
	(*DeleteResponse)(nil),        // 4: api.v1.DeleteResponse
	(*CommitEntry)(nil),           // 5: api.v1.CommitEntry
	(*CommitRequest)(nil),         // 6: api.v1.CommitRequest
	(*CommitResponse)(nil),        // 7: api.v1.CommitResponse
	(*DoneRequest)(nil),           // 8: api.v1.DoneRequest
	(*DoneResponse)(nil),          // 9: api.v1.DoneResponse
	(*ExchangeCertsRequest)(nil),  // 10: api.v1.ExchangeCertsRequest
	(*ExchangeCertsResponse)(nil), // 11: api.v1.ExchangeCertsResponse
}
var file_api_v1_sync_proto_depIdxs = []int32{
	0,  // 0: api.v1.WriteRequest.blocks:type_name -> api.v1.ChangedBlock
	5,  // 1: api.v1.CommitRequest.entries:type_name -> api.v1.CommitEntry
	1,  // 2: api.v1.SyncService.Write:input_type -> api.v1.WriteRequest
	6,  // 3: api.v1.SyncService.Commit:input_type -> api.v1.CommitRequest
	3,  // 4: api.v1.SyncService.Delete:input_type -> api.v1.DeleteRequest
	8,  // 5: api.v1.SyncService.Done:input_type -> api.v1.DoneRequest
	10, // 6: api.v1.SyncService.ExchangeCerts:input_type -> api.v1.ExchangeCertsRequest
	2,  // 7: api.v1.SyncService.Write:output_type -> api.v1.WriteResponse
	7,  // 8: api.v1.SyncService.Commit:output_type -> api.v1.CommitResponse
	4,  // 9: api.v1.SyncService.Delete:output_type -> api.v1.DeleteResponse
	9,  // 10: api.v1.SyncService.Done:output_type -> api.v1.DoneResponse
	11, // 11: api.v1.SyncService.ExchangeCerts:output_type -> api.v1.ExchangeCertsResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_v1_sync_proto_init() }
func file_api_v1_sync_proto_init() {
	if File_api_v1_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_sync_proto_rawDesc), len(file_api_v1_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_sync_proto_goTypes,
		DependencyIndexes: file_api_v1_sync_proto_depIdxs,
		MessageInfos:      file_api_v1_sync_proto_msgTypes,
	}.Build()
	File_api_v1_sync_proto = out.File
	file_api_v1_sync_proto_goTypes = nil
	file_api_v1_sync_proto_depIdxs = nil
}
